### ISSUE TITLE
resolve dns with ingress configuration after connecting kubevpn

### ISSUE THREAD

**Issue by gudipudipradeep** [wencaiwulue/kubevpn#14]
resolve dns with ingress configuration after connecting kubevpn.
without depending on the global dns configuration of using system.

**Comment by wencaiwulue** [comment]
> 

yes, it use cluster dns resolve, i did some work to support cluster dns resolve in local

**Comment by wencaiwulue** [comment]
> resolve dns with ingress configuration after connecting kubevpn. without depending on the global dns configuration of using system.

you can use latest version v1.1.11 to have a try

**Comment by gudipudipradeep** [comment]
@wencaiwulue when I am using latest version it is disconnecting my cisco, Unless cisco vpn we cann't able to access our cluster. Please can help on this.

**Comment by wencaiwulue** [comment]
> @wencaiwulue when I am using latest version it is disconnecting my cisco, Unless cisco vpn we cann't able to access our cluster. Please can help on this.
> 
> 1. Always asking admin permission whenever kubevpn connect. is it possible to make it like installer while installing it ask admin permissions windows.

First, about disconneting, i am wondering whether pod or service cidr range is contains your cisco vpn server ip 🤔
Second, maybe i can learn how to write a GUI desktop software on windows, i know some go library can help me, but it is still not a small challenge 😂

**Comment by alejandromiller21** [comment]
I was unable to install Kubevpn on Mac OS. I would like to know how to install it.

**Comment by wencaiwulue** [comment]
> I was unable to install Kubevpn on Mac OS. I would like to know how to install it.

it is a executable binary, [link](https://github.com/wencaiwulue/kubevpn/releases/tag/v1.1.14) you can download from here, chmod add exec permission and move it to /usr/local/bin/kubevpn

just like 
`wget https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.14/kubevpn-darwin-amd64 -o kubevpn && chmod +x kubevpn && mv kubevpn /usr/local/bin/kube
vpn`

**Comment by alejandromiller21** [comment]
That's great! Unfortunately, it doesn't work. I have followed all the steps, but I have this message: permission denied: kubevpn

**Comment by wencaiwulue** [comment]
> That's great! Unfortunately, it doesn't work. I have followed all the steps, but I have this message: permission denied: kubevpn

sorry, it's my fault, command should like this `wget https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.14/kubevpn-darwin-amd64 -o kubevpn && chmod +x kubevpn && sudo mv kubevpn /usr/local/bin/kubevpn`

after downloaded, you need to type your PC password allow to mv it to /usr/local/bin folder

**Comment by gudipudipradeep** [comment]
@wencaiwulue can we plan small icon gui program to help. like task bar status one.
![image](https://user-images.githubusercontent.com/8638634/215057244-d36cbaa1-7bcc-4648-9032-ad774f67c22a.png)

**Comment by wencaiwulue** [comment]
@gudipudipradeep yes, it's a good idea, more easier to use on Windows, maybe you can develop this feature, let's do it together ！！！
