### ISSUE TITLE
kubevpn dev check resource before running

### ISSUE THREAD

**Issue by ealyn** [wencaiwulue/kubevpn#18]
I got docker 137 return code.
Can kubevpn check if docker desktop resource config satisfy remote k8s resource limit, and log WARN while not?

**Comment by wencaiwulue** [comment]
good idea, i will add precheck logic next version

**Comment by wencaiwulue** [comment]
already add precheck logic, commit: https://github.com/wencaiwulue/kubevpn/commit/30a82e25eb7e2792f9f76716fb161d9c078b98f3
