### ISSUE TITLE
kubevpn listen on 6060 cause port conflict

### ISSUE THREAD

**Issue by joyme123** [wencaiwulue/kubevpn#20]
Port 6060 is a well-known port. It is used for golang pprof. So kubevpn's port will be conflict with other golang programs. It is better to use ports that are rarely used.

**Comment by wencaiwulue** [comment]
already change port to 32345 , commit: https://github.com/wencaiwulue/kubevpn/commit/a545f3a9589809b20e62950eb213a1680d37367a
