### ISSUE TITLE
Facing connection issue.

### ISSUE THREAD

**Issue by gudipudipradeep** [wencaiwulue/kubevpn#36]
![image](https://user-images.githubusercontent.com/8638634/232120817-162b5252-24af-4d8d-9304-bbefb4a795e6.png)
![image](https://user-images.githubusercontent.com/8638634/232120923-b6c0976a-cd5d-4688-897d-5d7b2d50e6e2.png)
Please can you guide me what was the problem.

**Comment by wencaiwulue** [comment]
> ![image](https://user-images.githubusercontent.com/8638634/232120817-162b5252-24af-4d8d-9304-bbefb4a795e6.png) ![image](https://user-images.githubusercontent.com/8638634/232120923-b6c0976a-cd5d-4688-897d-5d7b2d50e6e2.png) Please can you guide me what was the problem.

it is normal updating cluster deployment kubevpn-traffic-manager image, because you are using newer client, we recommand that kubevpn client version should same as container image version

**Comment by wencaiwulue** [comment]
just wait it upgrade finished

**Comment by gudipudipradeep** [comment]
Waiting long amount time before reporting.. Can we enable debug mode or source code to run directly to understand what was the issue is...?

**Comment by wencaiwulue** [comment]
maybe because image can not
pull image？you can describe pod to see k8s event, and more,kubevpn is open source for everyone you can check code to see what did it do

**Comment by wencaiwulue** [comment]
> Waiting long amount time before reporting.. Can we enable debug mode or source code to run directly to understand what was the issue is...?

here is a flag `--debug`, you can see more log

**Comment by gudipudipradeep** [comment]
@wencaiwulue  Please can you guide me, how we can run the code locally. 
I checkout the code.
install the Go..
Need your inputs to run the project locally.

Am new to go :) Please help to me run.

**Comment by gudipudipradeep** [comment]
@wencaiwulue 
C:\ci_projects\kubevpn\cmd\kubevpn>go run main.go connect
got cidr from cache
update ref count successfully
traffic manager already exist, reuse it
port forward ready
tunnel connected
Get "https://aks-xxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io:443/api/v1/pods?timeout=30s&timeoutSeconds=30": read tcp 10.68.141.47:63213->10.21.105.196:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
prepare to exit, cleaning up
failed to release ip to dhcp, err: failed to get cm DHCP server, err: Get "https://aks-xxxxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io:443/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": context deadline exceeded
can not update ref-count: update ref-count failed, increment: -1, error: client rate limiter Wait returned an error: context deadline exceeded
clean up successful

Getting above issue.
it is disconnecting our organization ciso vpn connection to..

**Comment by wencaiwulue** [comment]
> @wencaiwulue C:\ci_projects\kubevpn\cmd\kubevpn>go run main.go connect got cidr from cache update ref count successfully traffic manager already exist, reuse it port forward ready tunnel connected Get "https://aks-xxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io:443/api/v1/pods?timeout=30s&timeoutSeconds=30": read tcp 10.68.141.47:63213->10.21.105.196:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. prepare to exit, cleaning up failed to release ip to dhcp, err: failed to get cm DHCP server, err: Get "https://aks-xxxxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io:443/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": context deadline exceeded can not update ref-count: update ref-count failed, increment: -1, error: client rate limiter Wait returned an error: context deadline exceeded clean up successful
> 
> Getting above issue. it is disconnecting our organization ciso vpn connection to.. using azure cloud aks private cluster

here is link to binary , not need to build it manally, [kubevpn_v1.1.30_windows_amd64.zip](https://github.com/wencaiwulue/kubevpn/releases/download/v1.1.30/kubevpn_v1.1.30_windows_amd64.zip)

**Comment by wencaiwulue** [comment]
> "[https://aks-xxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io](https://aks-xxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io:443/api/v1/pods?timeout=30s&timeoutSeconds=30)

you can parse command output: `kubectl get cm kubevpn-traffic-manager -o yaml`  and `nslookup https://aks-xxxx-rg-wwwww-nonpr-8de222c5-0754bde13.hcp.eastus.azmk8s.io` ?

**Comment by wencaiwulue** [comment]
@gudipudipradeep hello, it should be solved in this [commit](https://github.com/wencaiwulue/kubevpn/commit/c26f9495e0eef715da9c407da73f3815d3bcadde), can you clone this repo and pull latest code, run command `make kubevpn` to build binary, and try it again?

**Comment by wencaiwulue** [comment]
@gudipudipradeep you can try latest version v1.1.31 to verify this bug whether fixed or not ~
