### ISSUE TITLE
Unable to delete the pods in cluster

### ISSUE THREAD

**Issue by gudipudipradeep** [wencaiwulue/kubevpn#37]
![image](https://user-images.githubusercontent.com/8638634/232125633-7dd3760a-bae1-4529-acb1-8976e8028b56.png)
Not able to delete these pods from the cluster even after applying the force

**Comment by wencaiwulue** [comment]
> ![image](https://user-images.githubusercontent.com/8638634/232125633-7dd3760a-bae1-4529-acb1-8976e8028b56.png) Not able to delete these pods from the cluster even after applying the force

you can use command `kubevpn reset` to delete resources if you don't need it anymore, you can not delete pod if it has a controller, like rs or sts
