### ISSUE TITLE
its possible run without sudo or root user ?

### ISSUE THREAD

**Issue by abdidarmawan007** [wencaiwulue/kubevpn#5]
its possible run without sudo or root user ?

kubevpn connect --namespace=staging

```
INFO[0000] [sudo kubevpn connect --namespace=staging]   
2022/01/11 11:30:53 connect.go:40: stat /root/.kube/config: no such file or directory
WARN[0000] exit status 1
```

for example i have user = user123 with kubeconfig in
```
/home/user123/.kube/config
```
running tools is not good as root

**Comment by wencaiwulue** [comment]
> its possible run without sudo or root user ?
> 
> kubevpn connect --namespace=staging
> 
> ```
> INFO[0000] [sudo kubevpn connect --namespace=staging]   
> 2022/01/11 11:30:53 connect.go:40: stat /root/.kube/config: no such file or directory
> WARN[0000] exit status 1
> ```
> 
> for example i have user = user123 with kubeconfig in
> 
> ```
> /home/user123/.kube/config
> ```
> 
> running tools is not good as root

please use command `kubevpn connect --namespace=staging --kubeconfig=/home/user123/.kube/config
`

**Comment by wencaiwulue** [comment]
yes, i know this issue before, but i did't found any good solution, you can use abstract file path to avoid this issue

**Comment by abdidarmawan007** [comment]
okay thanks

**Comment by wencaiwulue** [comment]
i already fix this bug, now you can build a kubevpn manually，and use command `kubevpn connect --namespace=staging`, it works fine, thanks to for report this issue :)

**Comment by wencaiwulue** [comment]
> > its possible run without sudo or root user ?
> > kubevpn connect --namespace=staging
> > ```
> > INFO[0000] [sudo kubevpn connect --namespace=staging]   
> > 2022/01/11 11:30:53 connect.go:40: stat /root/.kube/config: no such file or directory
> > WARN[0000] exit status 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > for example i have user = user123 with kubeconfig in
> > ```
> > /home/user123/.kube/config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > running tools is not good as root
> 
> please use command `kubevpn connect --namespace=staging --kubeconfig=/home/user123/.kube/config `

already fix it
