### ISSUE TITLE
Reverse-proxy mode, cannot connect.

### ISSUE THREAD

**Issue by mustufa5689** [wencaiwulue/kubevpn#6]
Hello Team,

While kubeVPN works well in connecting the services,pods from local laptop using directly POD ID and via Services name using CURL client.

However, I am facing issues, where in reverse proxy mode seems to be not working. It deletes my existing service name automatically.

Steps:
- Create the services,deployments with name myapp having nginx as an image.
- When running command, it says that the service does not exists. 

~~~
kubevpn connect --namespace=test --workloads=service/myapp 
INFO[0000] [sudo kubevpn connect --namespace=test --workloads=service/myapp]
2022/01/20 14:28:32 connect.go:295: kubeconfig path: /Users/myname/.kube/config, namespace: test, serivces: [service/myapp]
2022/01/20 14:28:34 util.go:214: services "myapp" not found
2022/01/20 14:28:38 cleaner.go:74: update ref count successfully
2022/01/20 14:28:40 util.go:214: services "myapp" not found
2022/01/20 14:28:40 connect.go:81: services "myapp" not found
2022/01/20 14:28:40 connect.go:43: services "myapp" not found
WARN[0008] exit status 1 
~~~

- However the services gets deleted when running the above command. Seems kubevpn --workloads is not working for pods, deployments, services.

Please suggest.

Thanks,
Mustufa M.

**Comment by wencaiwulue** [comment]
let me think about it,  can you make sure service myapp is exist in namespace test? it seems like service-myapp not exist, kubevpn would not delete service, it will create a pod with same label with service-myapp, please make sure you are using latest version(build it by yourself like command `make kubevpn`, because of released package is out of date), and also try command `kubevpn connect -n test --workloads=deployments/myapp`

**Comment by wencaiwulue** [comment]
> 
it should works fine with deployment, replicas, service,statefulset, even support CRD in theroy

**Comment by wencaiwulue** [comment]
> let me think about it, can you make sure service myapp is exist in namespace test? it seems like service-myapp not exist, kubevpn would not delete service, it will create a pod with same label with service-myapp, please make sure you are using latest version(build it by yourself like command `make kubevpn`, because of released package is out of date), and also try command `kubevpn connect -n test --workloads=deployments/myapp`

sorry, build command should be `make kubevpn-macos`

**Comment by wencaiwulue** [comment]
> Hello Team,
> 
> While kubeVPN works well in connecting the services,pods from local laptop using directly POD ID and via Services name using CURL client.
> 
> However, I am facing issues, where in reverse proxy mode seems to be not working. It deletes my existing service name automatically.
> 
> Steps:
> 
> * Create the services,deployments with name myapp having nginx as an image.
> * When running command, it says that the service does not exists.
> 
> ```
> kubevpn connect --namespace=test --workloads=service/myapp 
> INFO[0000] [sudo kubevpn connect --namespace=test --workloads=service/myapp]
> 2022/01/20 14:28:32 connect.go:295: kubeconfig path: /Users/myname/.kube/config, namespace: test, serivces: [service/myapp]
> 2022/01/20 14:28:34 util.go:214: services "myapp" not found
> 2022/01/20 14:28:38 cleaner.go:74: update ref count successfully
> 2022/01/20 14:28:40 util.go:214: services "myapp" not found
> 2022/01/20 14:28:40 connect.go:81: services "myapp" not found
> 2022/01/20 14:28:40 connect.go:43: services "myapp" not found
> WARN[0008] exit status 1 
> ```
> 
> * However the services gets deleted when running the above command. Seems kubevpn --workloads is not working for pods, deployments, services.
> 
> Please suggest.
> 
> Thanks, Mustufa M.

oh, no you are right , this is a bug, i cann't believe it !!! ,  i screwed it up, deployment, statefulset, replicaset, CRD is works fine, tested it just now, i will fix it in two days, i am so sorry about that :(

**Comment by mustufa5689** [comment]
Yes, I know, it all removes the services,pods,deployments. It only works fine with the namespace option while running the kubeVPN.

Please share more doc for Connecting the Local services from External services. On the github page, the steps isn't helpfull. We want to use kubeVPN for most of our team members.

Thanks,
Mustufa M

**Comment by wencaiwulue** [comment]
> 

1，kubeVPN will not remove anything except this service bug，if workloads is deployment, statefulset, replicaset or another CRD, it will patch another sidecar, to capture all traffic and forward it to local though tunnel. so reverse function  works fine with those workloads

2, you are right,  wrong spelling

3, ok let me update doc and make it more helpful, thanks for your suggestion👍.

**Comment by mustufa5689** [comment]
For 3. I need more detail steps.

1. Run a deployment in test ns.
2. From the pod (created by the deployment), exec inside it and curl on the local services on the laptop?
3. If point [2], is valid, then does it makes a connection from the pod to any interface or only on the tunnel interface created by kubevpn?
Thanks,
Mustufa M.

**Comment by mustufa5689** [comment]
Hi, I can confirm that for the deployment, it created a Vpn sidecar container, and created the iptables PREROUTING chains to be sent to the local machine.

Thanks,
Mustufa M.

**Comment by wencaiwulue** [comment]
> For 1. it even does not work with the --workload=pod also. Please check that too.
> 
> For 3. I need more detail steps.
> 
> 1. Run a deployment in test ns..
> 2. From the pod (created by the deployment), exec inside it and curl on the local services on the laptop?
> 3. If point [2], is valid, then does it makes a connection from the pod to any interface or only on the tunnel interface created by kubevpn?
>    Thanks,
>    Mustufa M.

1, i tested workloads pods, it works fine, workloads=services bug still exists
2, `From the pod (created by the deployment), exec inside it and curl on the local services on the laptop?` yes, you can do it cause all of inbound traffic will be captured and forward it to local laptop
3, only on the tunnel interface created by kubevpn
4, as you can see, using iptables to capture all inbound traffic

**Comment by wencaiwulue** [comment]
> 

yes, you are right, using iptables captured traffic

**Comment by wencaiwulue** [comment]
> > For 1. it even does not work with the --workload=pod also. Please check that too.
> > For 3. I need more detail steps.
> > 
> > 1. Run a deployment in test ns..
> > 2. From the pod (created by the deployment), exec inside it and curl on the local services on the laptop?
> > 3. If point [2], is valid, then does it makes a connection from the pod to any interface or only on the tunnel interface created by kubevpn?
> >    Thanks,
> >    Mustufa M.
> 
> 1, i tested workloads pods, it works fine, workloads=services bug still exists 2, `From the pod (created by the deployment), exec inside it and curl on the local services on the laptop?` yes, you can do it cause all of inbound traffic will be captured and forward it to local laptop 3, only on the tunnel interface created by kubevpn 4, as you can see, using iptables to capture all inbound traffic

i tested --workloads=pods/podName, if this pod is not controlled by controllers , then it will have bug. you are right, forgive me my recession. i have fix it and test it, you can have a try

**Comment by wencaiwulue** [comment]
> Hello Team,
> 
> While kubeVPN works well in connecting the services,pods from local laptop using directly POD ID and via Services name using CURL client.
> 
> However, I am facing issues, where in reverse proxy mode seems to be not working. It deletes my existing service name automatically.
> 
> Steps:
> 
> * Create the services,deployments with name myapp having nginx as an image.
> * When running command, it says that the service does not exists.
> 
> ```
> kubevpn connect --namespace=test --workloads=service/myapp 
> INFO[0000] [sudo kubevpn connect --namespace=test --workloads=service/myapp]
> 2022/01/20 14:28:32 connect.go:295: kubeconfig path: /Users/myname/.kube/config, namespace: test, serivces: [service/myapp]
> 2022/01/20 14:28:34 util.go:214: services "myapp" not found
> 2022/01/20 14:28:38 cleaner.go:74: update ref count successfully
> 2022/01/20 14:28:40 util.go:214: services "myapp" not found
> 2022/01/20 14:28:40 connect.go:81: services "myapp" not found
> 2022/01/20 14:28:40 connect.go:43: services "myapp" not found
> WARN[0008] exit status 1 
> ```
> 
> * However the services gets deleted when running the above command. Seems kubevpn --workloads is not working for pods, deployments, services.
> 
> Please suggest.
> 
> Thanks, Mustufa M.

already fix --workloads=serivce and --workloads=pod, sorry for waiting so long, because spring festival is coming, a little bit losing myself

**Comment by wencaiwulue** [comment]
already fix it
