### ISSUE TITLE
2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:53651->10.61.89.222:53: i/o timeout

### ISSUE THREAD

**Issue by mustufa5689** [wencaiwulue/kubevpn#7]
Hello Team,

Please check on the below issue, it says timeout and cannot connect to the local services.

~~~
Forwarding from 0.0.0.0:10800 -> 10800
2022/02/10 10:47:18 connect.go:165: port forward ready
2022/02/10 10:47:18 connect.go:186: your ip is 223.254.254.117
2022/02/10 10:47:18 connect.go:190: tunnel connected
Handling connection for 10800
2022/02/10 10:47:21 connect.go:202: dns service ok
2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:53651->10.61.89.222:53: i/o timeout
2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:61890->10.61.89.222:53: i/o timeout
2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:49355->10.61.89.222:53: i/o timeout
2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:58423->10.61.89.222:53: i/o timeout
2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:58097->10.61.89.222:53: i/o timeout
2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:60749->10.61.89.222:53: i/o timeout
2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:58175->10.61.89.222:53: i/o timeout
2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:57496->10.61.89.222:53: i/o timeout
~~~

**Comment by wencaiwulue** [comment]
> Hello Team,
> 
> Please check on the below issue, it says timeout and cannot connect to the local services.
> 
> ```
> Forwarding from 0.0.0.0:10800 -> 10800
> 2022/02/10 10:47:18 connect.go:165: port forward ready
> 2022/02/10 10:47:18 connect.go:186: your ip is 223.254.254.117
> 2022/02/10 10:47:18 connect.go:190: tunnel connected
> Handling connection for 10800
> 2022/02/10 10:47:21 connect.go:202: dns service ok
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:53651->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:61890->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:49355->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:58423->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:58097->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:60749->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:58175->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:57496->10.61.89.222:53: i/o timeout
> ```

a little bit odd, let figure out something: 
1, can you ping pod ip under this circumstance ？
2, 10.61.89.222:53 should be remote k8s DNS service or dns pod ip,  can you make sure  it is correct? 
3, 10.61.64.0 is your local computer ip ?
4, can you use command `nslookup SERVICENAME 10.61.89.222` to verify DNS server is works fine or not ?
5, cat /etc/resolver/local, see output, like bellow: 
`➜  ~ cat /etc/resolver/local
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 127.0.0.1
port 49475
options ndots:5
options timeout:1`

**Comment by mustufa5689** [comment]
Hi,

It says connected now.

But still cant reach to the POD nor to any services via nslookup.

```
Forwarding from 0.0.0.0:10800 -> 10800
2022/02/10 11:46:48 connect.go:165: port forward ready
2022/02/10 11:46:48 connect.go:186: your ip is 223.254.254.117
2022/02/10 11:46:48 connect.go:190: tunnel connected
Handling connection for 10800
2022/02/10 11:46:52 connect.go:202: dns service ok
```

```
cat /etc/resolver/local 
search XYZ.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 127.0.0.1
port 56139
options ndots:5
options timeout:1
```

```
nslookup abc.<namespace>.svc.cluster.local
Server:		10.4.XX.10
Address:	10.4.XX.10#53

** server can't find abc.<namespace>.svc.cluster.local: NXDOMAIN
```

I have Omitted the results due to security concerns.

Thanks,
Mustufa M

**Comment by wencaiwulue** [comment]
> Hi,
> 
> It says connected now.
> 
> But still cant reach to the POD nor to any services via nslookup.
> 
> ```
> Forwarding from 0.0.0.0:10800 -> 10800
> 2022/02/10 11:46:48 connect.go:165: port forward ready
> 2022/02/10 11:46:48 connect.go:186: your ip is 223.254.254.117
> 2022/02/10 11:46:48 connect.go:190: tunnel connected
> Handling connection for 10800
> 2022/02/10 11:46:52 connect.go:202: dns service ok
> ```
> 
> ```
> cat /etc/resolver/local 
> search XYZ.svc.cluster.local svc.cluster.local cluster.local ec2.internal
> nameserver 127.0.0.1
> port 56139
> options ndots:5
> options timeout:1
> ```
> 
> ```
> nslookup abc.<namespace>.svc.cluster.local
> Server:		10.4.XX.10
> Address:	10.4.XX.10#53
> 
> ** server can't find abc.<namespace>.svc.cluster.local: NXDOMAIN
> ```
> 
> I have Omitted the results due to security concerns.
> 
> Thanks, Mustufa M

can you access with full dns ? like: open broswer, if you installed app bookinfo , then type `productpage.NAMESPACE.svc.cluster.local:9080` and enter

**Comment by mustufa5689** [comment]
Hi,

Able to access the Web page :)

But nslookup and ping to the POD still failing.

Below is the Ping reply

```
Request timeout for icmp_seq 138
Request timeout for icmp_seq 139
Request timeout for icmp_seq 140
Request timeout for icmp_seq 141
Request timeout for icmp_seq 142
Request timeout for icmp_seq 143
Request timeout for icmp_seq 144
Request timeout for icmp_seq 145
Request timeout for icmp_seq 146
Request timeout for icmp_seq 147
Request timeout for icmp_seq 148
```

**Comment by wencaiwulue** [comment]
> 

you are ping podIP or ping pod name ?

**Comment by wencaiwulue** [comment]
> Hi,
> 
> Able to access the Web page :)
> 
> But nslookup and ping to the POD still failing.
> 
> Below is the Ping reply
> 
> ```
> Request timeout for icmp_seq 138
> Request timeout for icmp_seq 139
> Request timeout for icmp_seq 140
> Request timeout for icmp_seq 141
> Request timeout for icmp_seq 142
> Request timeout for icmp_seq 143
> Request timeout for icmp_seq 144
> Request timeout for icmp_seq 145
> Request timeout for icmp_seq 146
> Request timeout for icmp_seq 147
> Request timeout for icmp_seq 148
> ```

you are ping podIP or ping pod name ?

**Comment by wencaiwulue** [comment]
> Hi,
> 
> Able to access the Web page :)
> 
> But nslookup and ping to the POD still failing.
> 
> Below is the Ping reply
> 
> ```
> Request timeout for icmp_seq 138
> Request timeout for icmp_seq 139
> Request timeout for icmp_seq 140
> Request timeout for icmp_seq 141
> Request timeout for icmp_seq 142
> Request timeout for icmp_seq 143
> Request timeout for icmp_seq 144
> Request timeout for icmp_seq 145
> Request timeout for icmp_seq 146
> Request timeout for icmp_seq 147
> Request timeout for icmp_seq 148
> ```

you can only ping pod which status is running normally, if you are ping a pod which status is completed, it will accour error like this

**Comment by mustufa5689** [comment]
Hi,

My pod is running only, also kubeVPN connected.

```
Forwarding from 0.0.0.0:10800 -> 10800
2022/02/10 12:40:32 connect.go:165: port forward ready
2022/02/10 12:40:32 connect.go:186: your ip is 223.254.254.117
2022/02/10 12:40:32 connect.go:190: tunnel connected
Handling connection for 10800
2022/02/10 12:40:34 connect.go:202: dns service ok
```


```
nginx-d5wtt                      1/1     Running   0          26h     10.61.86.157    ip-X-X-X-X.ec2.internal    <none>           <none>
```

ping 10.61.86.157
PING 10.61.86.157 (10.61.86.157): 56 data bytes
Request timeout for icmp_seq 0

**Comment by wencaiwulue** [comment]
> 

can you check your local route table, if you are using macOS, use `netstat -anr | grep 10.61`, linux using `route -n | grep 10.61`, i am thinking maybe it's confilct with your local network route setting

**Comment by wencaiwulue** [comment]
> > 
> 
> can you check your local route table, if you are using macOS, use `netstat -anr | grep 10.61`, linux using `route -n | grep 10.61`, i am thinking maybe it's confilct with your local network route setting

please paste output，let me analyse it

**Comment by mustufa5689** [comment]
netstat -anr | grep 10.61
10.61/16           utun4              USc          utun4       
10.61.10.251       10.176.32.40       UGHWIig      utun2       
10.61.64/18        10.61.64.1         UCS          utun3       
10.61.64.1         10.61.64.0         UH           utun3

**Comment by wencaiwulue** [comment]
> utun3


i got it, that right, utun3 is conflict with utun4, you can use command `sudo ifconfig utun3 down` to disable utun3 for temporary, then you should can ping pod ip sucessfully

**Comment by wencaiwulue** [comment]
> netstat -anr | grep 10.61 10.61/16 utun4 USc utun4 10.61.10.251 10.176.32.40 UGHWIig utun2 10.61.64/18 10.61.64.1 UCS utun3 10.61.64.1 10.61.64.0 UH utun3

i got it, that right, utun3 is conflict with utun4, you can use command `sudo ifconfig utun3 down` to disable utun3 for temporary, then you should can ping pod ip sucessfully

**Comment by mustufa5689** [comment]
> > netstat -anr | grep 10.61 10.61/16 utun4 USc utun4 10.61.10.251 10.176.32.40 UGHWIig utun2 10.61.64/18 10.61.64.1 UCS utun3 10.61.64.1 10.61.64.0 UH utun3
> 
> i got it, that right, utun3 is conflict with utun4, you can use command `sudo ifconfig utun3 down` to disable utun3 for temporary, then you should can ping pod ip sucessfully

Yes, able to work now

ping 10.61.93.189
PING 10.61.93.189 (10.61.93.189): 56 data bytes
64 bytes from 10.61.93.189: icmp_seq=0 ttl=252 time=232.482 ms
64 bytes from 10.61.93.189: icmp_seq=1 ttl=252 time=232.113 ms
64 bytes from 10.61.93.189: icmp_seq=2 ttl=252 time=235.302 ms

**Comment by wencaiwulue** [comment]
> 

I am so sorry about that, cause i know this issue before, even i add this task to the bottom of todo.md, i will fix it in this weekend, feel so sorry

**Comment by wencaiwulue** [comment]
> > > netstat -anr | grep 10.61 10.61/16 utun4 USc utun4 10.61.10.251 10.176.32.40 UGHWIig utun2 10.61.64/18 10.61.64.1 UCS utun3 10.61.64.1 10.61.64.0 UH utun3
> > 
> > 
> > i got it, that right, utun3 is conflict with utun4, you can use command `sudo ifconfig utun3 down` to disable utun3 for temporary, then you should can ping pod ip sucessfully
> 
> Yes, able to work now
> 
> ping 10.61.93.189 PING 10.61.93.189 (10.61.93.189): 56 data bytes 64 bytes from 10.61.93.189: icmp_seq=0 ttl=252 time=232.482 ms 64 bytes from 10.61.93.189: icmp_seq=1 ttl=252 time=232.113 ms 64 bytes from 10.61.93.189: icmp_seq=2 ttl=252 time=235.302 ms

I am so sorry about that, cause i know this issue before, even i add this task to the bottom of todo.md, i will fix it in this weekend, feel so sorry

**Comment by wencaiwulue** [comment]
> Hello Team,
> 
> Please check on the below issue, it says timeout and cannot connect to the local services.
> 
> ```
> Forwarding from 0.0.0.0:10800 -> 10800
> 2022/02/10 10:47:18 connect.go:165: port forward ready
> 2022/02/10 10:47:18 connect.go:186: your ip is 223.254.254.117
> 2022/02/10 10:47:18 connect.go:190: tunnel connected
> Handling connection for 10800
> 2022/02/10 10:47:21 connect.go:202: dns service ok
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:53651->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:61890->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:49355->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:23 dnsserver.go:49: read udp 10.61.64.0:58423->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:58097->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:24 dnsserver.go:49: read udp 10.61.64.0:60749->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:58175->10.61.89.222:53: i/o timeout
> 2022/02/10 10:47:26 dnsserver.go:49: read udp 10.61.64.0:57496->10.61.89.222:53: i/o timeout
> ```

already fixed it
